<?php

namespace App\Models;

use App\Helpers\Utils;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property string $email
 * @property string first_name
 * @property mixed $phone_number
 * @property int id
 * @property mixed $last_name
 * @property mixed $name
 * @property mixed user_type
 * @method static create(array $array)
 */
class User extends Authenticatable
{
    use Notifiable;

    const IS_ADMIN = 1;
    const IS_NOT_ADMIN = 0;
    const ADMIN = 'admin';
    const EMPLOYEE = 'employee';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function (User $user) {
            $user->name = $user->getFullName();
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'name',
        'user_type',
        'phone_number',
        'international_number',
        'email',
        'password',
        'is_admin',
        'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'is_admin' => 'boolean',
        'is_active' => 'boolean',
    ];

    public function getFullName(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function isAdmin(): bool
    {
        return $this->user_type === User::ADMIN;
    }
}
